language: emacs-lisp
# until github supports elisp, actual "language" is ruby
env:
# don't neeed emacs-git-snapshot, don't want to add dependencies
# that are not part of standard Emacs install
- EVM_EMACS=emacs-24.3-bin
- EVM_EMACS=emacs-24.4-bin
install:
- export EMBATCH="emacs --batch --eval \"(require 'org)\""
- echo $SHELL
- sudo apt-get install aspell  # for ispell
- sudo mkdir /usr/local/evm
- sudo chown $(id -u):$(id -g) /usr/local/evm
- curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
- export PATH="$HOME/.evm/bin:$PATH"
- evm install $EVM_EMACS --use > /dev/null
# verify that we're using the right f'ing Emacs
- emacs --version
# user-specific files need to be under name of travis user
- cp lloyd.org $(whoami).org
# emacs 24.3 will hang on confirmation dialog if semanticdb/ not present
- echo -e "paradox-github-token=not_secret\n" > ~/.emacs-secret
# we need ert-runner for testing, but don't want to require it for users
- emacs --batch --eval "(require 'org)" --eval '(org-babel-load-file "test/install-ert-runner.org")'
- ls ${HOME}/.emacs.d
- mkdir ${HOME}/.emacs.d/semanticdb/
- echo "==========================================================="
- echo "Begin tests"
- echo "==========================================================="
script:
- make test
