language: ruby
# ruby is default language; doesn't matter until github supports
# emacs-lisp
env:
# don't neeed emacs-git-snapshot, don't want to add dependencies
# that are not part of standard Emacs install
- EVM_EMACS=emacs-24.3-bin
install:
- sudo mkdir /usr/local/evm
- sudo chown $(id -u):$(id -g) /usr/local/evm
- curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
- export PATH="$HOME/.evm/bin:$PATH"
- evm install $EVM_EMACS --use > /dev/null
# verify that we're using the right f'ing Emacs
- emacs --version
- curl -fsSkL https://raw.github.com/cask/cask/master/go | python
- emacs --batch --eval "(starter-kit-install-if-needed 'ert-runner)"
- cd test
- make
- cd ..
script:
- cask exec ert-runner
