#!/usr/bin/env bash
# -*- coding: utf-8-unix; -*-
for EFILE in *.el
do   CFILE=${EFILE}c
     if [[ -f ${CFILE} ]]; then
         if [[ ${EFILE} -nt ${CFILE} ]]; then
             echo ${EFILE}
         fi
     fi
done
