#!/usr/bin/env bash
# -*- coding: utf-8-unix; -*-
#why don't i just do this in python?
for EFILE in *.el
do
    case ${EFILE} in
        ede-projects.el | srecode-map.el | custom.el) ;;
        *) CFILE=${EFILE}c
            if [[ -f ${CFILE} ]]; then
                if [[ ${EFILE} -nt ${CFILE} ]]; then
                    echo ${EFILE} is newer than ${CFILE}.
                fi
            else
                echo ${CFILE} missing.
             fi;;
     esac
done
